dist: xenial
language: python
python:
  - "3.6"
  - "3.7"


jdk:
  - oraclejdk8

env:
  global:
    - SPARK_HOME=/tmp/spark-2.4.1-bin-hadoop2.7

before_install:
  - chmod +x install-spark.sh
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install coveralls

install:
  - ./install-spark.sh
  - "pip install -r requirements.txt --progress-bar=off"


deploy:
  provider: pypi
  user: "prenigma"
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJGRiNzdmMTFiLTJlODktNGQxNC1hZmJhLTM2MzhlODZjNzBhNAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgAO4LEhjNwW_ZLL7Kzuxoysw-aLPdsfIBtIX-m9JYw7o"
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: develop-3.0

notifications:
  email: false
  


